#!/usr/bin/env python3

import sys

def factorize(num):
    factors = []
    for i in range(2, int(num ** 0.5) + 1):
        while num % i == 0:
            factors.append(i)
            num //= i
    if num > 1:
        factors.append(num)
    return factors

def main(file):
    with open(file, 'r') as f:
        numbers = f.readlines()
        for line in numbers:
            number = int(line)
            factors = factorize(number)
            print(f"{number}={'*'.join(map(str, factors[:2]))}")

if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: factors <file>")
        sys.exit(1)
    file = sys.argv[1]
    main(file)

